### ISSUE TITLE
angular 2

### ISSUE THREAD

**Issue by superstarmcawesome** [thatisuday/ng-image-gallery#40]
hey there,
really like your gallery! haven't found something like this in angular2! 
Are you thinking about upgrading the lib to angular 2?

**Comment by thatisuday** [comment]
@superstarmcawesome I might in near future. But can't at this moment.

**Comment by Ks89** [comment]
Hi. This is not spam. 
I want  to share my library that it is really similar to this one but for Angular 2. Obviously it's not the same, because I found this project only some weeks ago. 
I forked another repo, that probably was inspired by this project.
https://www.npmjs.com/package/angular-modal-gallery

What do you think? Do you have suggestions? 
@thatisuday if you want to contribute (in particular about css development) I'll really happy about that XD.

**Comment by thatisuday** [comment]
@Ks89 Great work. I will see how I can help once I get some free time.
